/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package besttrade;

/**
 *
 * @author User
 */
public class SearchItemScreen extends javax.swing.JPanel {

    /**
     * Creates new form SearchItemScreen
     */
    public SearchItemScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchField = new javax.swing.JTextField();
        filtersLabel = new javax.swing.JLabel();
        priceRange = new javax.swing.JComboBox<>();
        priceLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        zeroCheckBox = new javax.swing.JCheckBox();
        categoryLabel = new javax.swing.JLabel();
        bookCheckBox = new javax.swing.JCheckBox();
        furnitureCheckBox = new javax.swing.JCheckBox();
        vehicleCheckBox = new javax.swing.JCheckBox();
        viewMyProfileButton = new javax.swing.JButton();
        secondHandCheckBox = new javax.swing.JCheckBox();
        viewItemButton = new javax.swing.JButton();

        searchField.setText("search");
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        filtersLabel.setText("Filters");

        priceRange.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0-100", "100-200", "200-300", "300-..." }));
        priceRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceRangeActionPerformed(evt);
            }
        });

        priceLabel.setText("Price");

        typeLabel.setText("Type");

        zeroCheckBox.setText("Zero");
        zeroCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroCheckBoxActionPerformed(evt);
            }
        });

        categoryLabel.setText("Category");

        bookCheckBox.setText("Book");
        bookCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookCheckBoxActionPerformed(evt);
            }
        });

        furnitureCheckBox.setText("Furniture");

        vehicleCheckBox.setText("Vehicle");

        viewMyProfileButton.setText("View My Profile");
        viewMyProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMyProfileButtonActionPerformed(evt);
            }
        });

        secondHandCheckBox.setText("Second Hand");

        viewItemButton.setText("View Item");
        viewItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewItemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(secondHandCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vehicleCheckBox)
                            .addComponent(furnitureCheckBox)
                            .addComponent(bookCheckBox)
                            .addComponent(categoryLabel)
                            .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zeroCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(priceRange, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(59, 59, 59))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(filtersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(46, 46, 46)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                                .addComponent(viewMyProfileButton)
                                .addGap(28, 28, 28))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(viewItemButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filtersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(viewMyProfileButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoryLabel)
                .addGap(18, 18, 18)
                .addComponent(bookCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(furnitureCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vehicleCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(priceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(priceRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(viewItemButton)
                        .addGap(48, 48, 48)))
                .addComponent(typeLabel)
                .addGap(18, 18, 18)
                .addComponent(zeroCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(secondHandCheckBox)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void zeroCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zeroCheckBoxActionPerformed

    private void bookCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookCheckBoxActionPerformed

    private void viewMyProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMyProfileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewMyProfileButtonActionPerformed

    private void priceRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceRangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceRangeActionPerformed

    private void viewItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewItemButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewItemButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bookCheckBox;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel filtersLabel;
    private javax.swing.JCheckBox furnitureCheckBox;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JComboBox<String> priceRange;
    private javax.swing.JTextField searchField;
    private javax.swing.JCheckBox secondHandCheckBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JCheckBox vehicleCheckBox;
    private javax.swing.JButton viewItemButton;
    private javax.swing.JButton viewMyProfileButton;
    private javax.swing.JCheckBox zeroCheckBox;
    // End of variables declaration//GEN-END:variables
}
